/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/newsletter/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities/{capability}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["capability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NewsletterSubscriptionRequest: {
            email: string;
            consentVersion: string;
            source?: string;
            website?: string;
        };
        NewsletterSubscriptionResponse: {
            status?: string;
        };
        HealthResponse: {
            status?: string;
        };
        CapabilityDescriptorResponse: {
            /** @enum {string} */
            capability?: "GITHUB_ACTIVITY" | "GITHUB_REPOSITORIES" | "SPOTIFY_ON_REPEAT" | "INSTAGRAM_MEDIA" | "YOUTUBE_UPLOADS" | "LINKEDIN_SELECTED_POSTS" | "HOMELAB_SUMMARY";
            /** @enum {string} */
            componentType?: "ACTIVITY_TIMELINE" | "REPOSITORY_GRID" | "MUSIC_CARD" | "SOCIAL_GRID" | "HOMELAB_SUMMARY";
            dataEndpoint?: string;
            title?: string;
            sourceLabel?: string;
            /** Format: date-time */
            refreshedAt?: string;
        };
        CapabilitySnapshotResponse: {
            /** @enum {string} */
            capability?: "GITHUB_ACTIVITY" | "GITHUB_REPOSITORIES" | "SPOTIFY_ON_REPEAT" | "INSTAGRAM_MEDIA" | "YOUTUBE_UPLOADS" | "LINKEDIN_SELECTED_POSTS" | "HOMELAB_SUMMARY";
            /** @enum {string} */
            componentType?: "ACTIVITY_TIMELINE" | "REPOSITORY_GRID" | "MUSIC_CARD" | "SOCIAL_GRID" | "HOMELAB_SUMMARY";
            /** @enum {string} */
            state?: "ENABLED" | "DISABLED" | "AWAITING_AUTHORIZATION" | "HIDDEN" | "STALE" | "HEALTHY";
            title?: string;
            sourceLabel?: string;
            /** Format: date-time */
            refreshedAt?: string;
            content?: {
                [key: string]: Record<string, never>;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    subscribe: {
        parameters: {
            query?: never;
            header?: {
                Origin?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsletterSubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NewsletterSubscriptionResponse"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthz_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapabilityDescriptorResponse"][];
                };
            };
        };
    };
    capability: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                capability: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapabilitySnapshotResponse"];
                };
            };
        };
    };
}
